# -*- coding: utf-8 -*-
"""
Created on Wed Sep 17 14:57:08 2025

@author: cmn, adapted from J. Lukens

"""

import numpy as np
from numpy import kron
# from scipy.linalg import qr, svd
from datetime import datetime
# import plot_functions as pf
import density_matrices as dmat
from numba import njit

def run_tomography(counts,proj_order,th=9,bell_choice=2,make_plots=False,verbose=False,
                   rho_ref=[], Ua=[], Ub=[]):
    '''
    Run Quantum State Tomography with Bayesian reconstruction algorithm.

    Parameters
    ----------
    data_dir : STRING
        Input data directory.
    data_name : STRING
        Input data filename.
    th : INT, optional
        log2(thinning parameter). The default is 9.
    bell_choice : INT, optional
        Choice of target Bellstate. The default is 2.
            0 --> Phi +
            1 --> Phi -
            2 --> Psi +
            3 --> Psi -
    make_plots : BOOL, optional
        Option to plot raw count data. The default is False.
    rho_mle : Numpy ARRAY, optional
        Reference density matrix generated by MLE. The default is None.
    acc_subtract : BOOL, optional
        Subtract accidentals as input data is read. The default is False.

    Returns
    -------
    result : TYPE
        DESCRIPTION.

    '''
    
    #TODO: include option for 16-projection tomography
    K0 = np.sum(counts)/9
    
    M = meas_matrix(proj_order)
    
    # print(M)

    # Run MCMC
    THIN = 2**th
    
    if verbose:
        start_time = datetime.now()
        
    samp = two_qubit_BP(counts, K0, M, THIN)
    
    if verbose:
        end_time = datetime.now()
        time_delta = end_time - start_time
        print(f"Sampler time: {time_delta.total_seconds()} s")
    
    result = analyze_samples(counts, K0, M, THIN, bell_choice, samp, rho_ref, Ua, Ub)
         
    return result

def meas_matrix(proj_order):
    '''
    Generate measurement matrix from list of polarization state projections.
    Contains map from basis names {H,V,D,A,R,L} onto complex vectors.

    Parameters
    ----------
    proj_order : LIST of pairs of STRINGs
        List of polarization basis state combinations ['a','b'].

    Returns
    -------
    M : NUMPY ARRAY
        Array of projection matrices, representing all listed input measurements.

    '''
    # Define basis kets
    basis = {
        'H': np.array([1, 0], dtype=complex),
        'V': np.array([0, 1], dtype=complex),
        'D': (1/np.sqrt(2)) * np.array([1, 1], dtype=complex),
        'A': (1/np.sqrt(2)) * np.array([1, -1], dtype=complex),
        'R': (1/np.sqrt(2)) * np.array([1, 1j], dtype=complex),
        'L': (1/np.sqrt(2)) * np.array([1, -1j], dtype=complex)
    }

    # Build measurement matrix M
    M = []
    for proj in proj_order:
        ket1 = basis[proj[0]]
        ket2 = basis[proj[1]]
        state = kron(ket1, ket2)
        proj_mat = kron(np.conj(state), state)
        M.append(proj_mat)
    M = np.array(M)
    
    return M

@njit
def two_qubit_BP(counts, K0, M, THIN):
    '''
    Main loop for Bayesian estimation.

    Parameters
    ----------
    counts : TYPE
        DESCRIPTION.
    K0 : TYPE
        DESCRIPTION.
    M : TYPE
        DESCRIPTION.
    psi : TYPE
        DESCRIPTION.
    THIN : TYPE
        DESCRIPTION.
    bell_choice : TYPE
        DESCRIPTION.
    rho_mle : TYPE
        DESCRIPTION.

    Returns
    -------
    result : TYPE
        DESCRIPTION.

    '''
    
    ##############################
    # INPUTS
    num_samp = 2**10    # Number of samples to obtain from MH
    D = 4               # Hilbert space dimension
    k = 0.1             # relative st.dev. for counts
    beta = 0.1          # initial stepsize
    
    Mb = 500            # Update stepsize after this many points
    r = 1.1             # Acceptance rate update factor
    
    ##############################
    # INITIAL VALUES FOR SAMPLER
    # np.random.seed()
    param0 = np.random.randn(4*D**2 + 1)
    
    ##############################
    # MH SAMPLER    
    # start_time = datetime.now()
    samp = np.zeros((num_samp, len(param0)))
    acc = 0

    # Initial point:
    x = param0
    rhoX = param_to_rho_col(x[:-1], D)
    Kx = K0 * (1 + k * x[-1])           # Flux value
    pr = np.real(M @ rhoX)              # probabilities
    logX = -Kx * np.sum(pr) + \
            np.dot(counts, np.log(Kx * pr)) #Likelihood

    samp_idx = 0
    for j in range(num_samp * THIN):
        # Proposed update parameters:
        y = np.sqrt(1 - beta**2) * x + beta * np.random.randn(len(x))
        rhoY = param_to_rho_col(y[:-1], D)
        Ky = K0 * (1 + k * y[-1])
        
        pr = np.real(M @ rhoY)
        logY = -Ky * np.sum(pr) + np.dot(counts, np.log(Ky * pr)) # New likelihood

        if np.log(np.random.rand()) < logY - logX:
            x = y           #Accept new point
            logX = logY
            acc += 1

        if (j + 1) % Mb == 0:       # Stepsize adaptation
            rat = acc / Mb          # Est. accept prob., keep near 0.234
            if rat > 0.6:
                beta = min(beta * r, 1.0)   #Cap beta at unity
            elif rat < 0.2:         
                beta /= r
            acc = 0

        if (j + 1) % THIN == 0: #Store samples
            samp[samp_idx] = x
            samp_idx += 1
            
    # end_time = datetime.now()
    
    return samp

#####################3 @njit
def analyze_samples(counts, K0, M, THIN, bell_choice,samp,rho_ref, Ua, Ub):
    
    D = 4        # Extract Hilbert space dimension
    k = 0.1             # relative st.dev. for counts
    
    num_samp = np.shape(samp)[0]
    
    # Analyze samples
    rhoEst = np.zeros((D, D, num_samp), dtype=complex)
    Kest = np.zeros(num_samp)
    # Eest = np.zeros(num_samp)
    rhoB = np.zeros((D, D), dtype=complex)  #Bayesian mean

    for n in range(num_samp):
        rho_vec = param_to_rho_col(samp[n, :-1], D)
        rho_mat = rho_vec.reshape((D, D)).T.conj() #conjugate needed (for some reason...)
        rhoEst[:, :, n] = rho_mat
        rhoB += rho_mat / num_samp
        
        # negvals = neg(rhoEst[:,:,n],D)
        # Eest[n] = np.log2(2*negvals+1)
        Kest[n] = K0 * (1 + k * samp[n, -1])
    
    if len(Ua) < 1 or len(Ub) < 1:
        Ua, Ub = dmat.beautify_2qubit(rhoB)
    
    # Ucor = kron(Ua, Ub)
    rhoC = dmat.compensate_2qubit(rhoB,Ua,Ub,bell_choice=bell_choice)
    
    rhoBell = dmat.generate_werner_2qubit(bell_choice)
    
    result = {
        'K': np.mean(Kest),
        'dK': np.std(Kest, ddof=1),
        # 'E': np.mean(Eest),
        # 'dE': np.std(Eest, ddof=1),
        'rhoB': rhoB,
        'rhoC': rhoC,
        'samp': samp,
        'THIN': THIN,
        'psi': rhoBell,
        'M': M,
        'Ua': Ua,
        'Ub': Ub,
        'counts': counts
    }
    
    # Fidelity calculations
    
    rho_ref = [rhoBell] + rho_ref
    
    num_refs = len(rho_ref)
    
    Fb = [np.zeros(num_samp) for rho0 in rho_ref]
    Fc = [np.zeros(num_samp) for rho0 in rho_ref]
    
    for i in range(num_refs):
        for n in range(num_samp):
            rho_raw = rhoEst[:, :, n]
            rho_rot = dmat.compensate_2qubit(rho_raw,Ua,Ub,bell_choice=bell_choice)
            
            Fb[i][n] = dmat.compute_fidelity(rho_raw, rho_ref[i])
            Fc[i][n] = dmat.compute_fidelity(rho_rot, rho_ref[i])

        result[f'F{i}b'] = np.mean(Fb[i])
        result[f'F{i}c'] = np.mean(Fc[i])
        result[f'dF{i}b'] = np.std(Fb[i], ddof=1)
        result[f'dF{i}c'] = np.std(Fc[i], ddof=1)

    return result


@njit
def param_to_rho_col(par, D):
    '''
    

    Parameters
    ----------
    par : TYPE
        DESCRIPTION.
    D : TYPE
        DESCRIPTION.

    Returns
    -------
    TYPE
        DESCRIPTION.

    '''
    # Ginibre draws 1 & 2
    G = par[0:D**2].reshape(D, D) + 1j * par[D**2:2*D**2].reshape(D, D)
    H = par[2*D**2:3*D**2].reshape(D, D) + 1j * par[3*D**2:4*D**2].reshape(D, D)
    
    # Find uniray from H (from QETLAB)
    Q, R = np.linalg.qr(H)
    V = Q * np.sign(np.diag(R))[:, np.newaxis]
    W = (np.eye(D) + V) @ G # Bures construction.
    
    rho = W @ W.conj().T
    rho /= np.trace(rho)
    
    return rho.T.flatten()

############### @njit
def neg(rho, D):
    '''
    

    Parameters
    ----------
    rho : TYPE
        DESCRIPTION.
    D : TYPE
        DESCRIPTION.

    Returns
    -------
    TYPE
        DESCRIPTION.

    '''
    rhoPT = np.zeros((D,D),dtype=complex) # initialize partial transpose
    d = int(np.sqrt(D))
    idx = np.arange(0,d*(d-1)+1,d)
    for r in idx:
        for c in idx:
            rhoPT[r:r+d,c:c+d] = np.transpose(rho[r:r+d,c:c+d])
    lam = np.real(np.linalg.eigvals(rhoPT))

    return -np.dot(lam<0,lam)

#######
# import numpy as np
# from numba import njit

@njit
def neg_alt(rho, D):
    """
    Compute negativity of a density matrix rho (dimension D x D)
    using partial transpose. Numba-compatible version.
    """
    # allocate partial transpose
    rhoPT = np.zeros((D, D), dtype=np.complex128)
    
    d = int(np.sqrt(D))

    # indices for block structure
    # (manual creation since np.arange(start, stop, step) with complex inputs can be tricky)
    idx = np.empty(d, dtype=np.int64)
    for k in range(d):
        idx[k] = k * d

    # partial transpose w.r.t. second subsystem
    for rr in range(d):
        r = idx[rr]
        for cc in range(d):
            c = idx[cc]
            # transpose the d×d block
            for i in range(d):
                for j in range(d):
                    rhoPT[r + i, c + j] = rho[r + j, c + i]

    # eigenvalues (rhoPT is Hermitian)
    lam = np.linalg.eigh(rhoPT)[0].real

    # negativity = sum of |negative eigenvalues|
    neg_sum = 0.0
    for i in range(len(lam)):
        if lam[i] < 0.0:
            neg_sum += -lam[i]

    return neg_sum

